<?php
return
    array(
        0 => array('id' => '1', 'po_name' => 'Samsung Gear Fit', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'male', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '20', 'po_brand' => 'Samsung', 'po_category' => 'Đồng hồ nam', 'po_provider' => 'Đồng Hồ Thông Minh Giá Rẻ'),
        1 => array('id' => '2', 'po_name' => 'Gear Pro Series 5', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'female', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '30', 'po_brand' => 'Gearfit', 'po_category' => 'Đồng hồ đôi Emoji', 'po_provider' => 'Công Ty TNHH Thương Mại Dịch Vụ XNK Hưng Việt Phát'),
        2 => array('id' => '3', 'po_name' => 'Fitbit Verrsa Pro', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'male', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '33', 'po_brand' => 'Fitbit', 'po_category' => 'Đồng hồ sức khỏe', 'po_provider' => 'Công Ty TNHH Thương Mại Lê Anh'),
        3 => array('id' => '4', 'po_name' => 'Samsung Gear Pro', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'female', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '10', 'po_brand' => 'Samsung', 'po_category' => 'Đồng hồ Seiko', 'po_provider' => 'Công Ty TNHH Thời Gian Thành Phố'),
        4 => array('id' => '5', 'po_name' => 'Huawei Watch Fit', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'male', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '15', 'po_brand' => 'Huawei', 'po_category' => 'Đồng hồ Philips', 'po_provider' => 'Công Ty TNHH Phát Triển & Thương Mại Duy Anh'),
        5 => array('id' => '6', 'po_name' => 'Huawei Watch Pro', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'female', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '6', 'po_brand' => 'Huawei', 'po_category' => 'Đồng hồ Seiko', 'po_provider' => 'Công Ty TNHH Một Thành Viên XD TM SX Dịch Vụ Xuất Khẩu Phương Đức'),
        6 => array('id' => '7', 'po_name' => 'Huawei Watch GT2', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'male', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '44', 'po_brand' => 'Huawei', 'po_category' => 'Đồng hồ nam', 'po_provider' => 'Công Ty CP XNK Hàng Hiệu Hoa Kỳ (HHHK JSC)'),
        7 => array('id' => '8', 'po_name' => 'Amazfit Gts nội địa', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'female', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '100', 'po_brand' => 'Fitbit', 'po_category' => 'Đồng hồ đôi Emoji', 'po_provider' => 'Công Ty TNHH MTV Thương Mại Dịch Vụ Quà Tặng Thiên Minh'),
        8 => array('id' => '9', 'po_name' => 'Amazfit Gts quốc tế', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'male', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '20', 'po_brand' => 'Fitbit', 'po_category' => 'Đồng hồ Omega', 'po_provider' => 'Công Ty TNHH Thương Mại Dịch Vụ XNK Hưng Việt Phát'),
        9 => array('id' => '10', 'po_name' => 'Xiaomi Amazfit Gts Vàng', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'female', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '24', 'po_brand' => 'Xiaomi', 'po_category' => 'Đồng hồ sức khỏe', 'po_provider' => 'Công Ty TNHH Phân Phối Sản Phẩm Cao Cấp LPD'),
        10 => array('id' => '11', 'po_name' => 'Huami Amazfit Gts', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'male', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '15', 'po_brand' => 'Gearfit', 'po_category' => 'Đồng hồ Omega', 'po_provider' => 'Đồng Hồ Thông Minh Giá Rẻ'),
        11 => array('id' => '12', 'po_name' => 'Xiaomi Amazfit Pink', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'female', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '76', 'po_brand' => 'Xiaomi', 'po_category' => 'Đồng hồ định vị', 'po_provider' => 'Công Ty TNHH Phát Triển & Thương Mại Duy Anh'),
        12 => array('id' => '13', 'po_name' => 'Xiaomi Amazfit gold', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'male', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '45', 'po_brand' => 'Xiaomi', 'po_category' => 'Đồng hồ định vị', 'po_provider' => 'Công Ty TNHH Sao Hỏa'),
        13 => array('id' => '14', 'po_name' => 'Xiaomi Amazfit Gts đen', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'female', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '67', 'po_brand' => 'Xiaomi', 'po_category' => 'Đồng hồ Epos swiss', 'po_provider' => 'Công Ty Cổ Phần TYP Việt Nam'),
        14 => array('id' => '15', 'po_name' => 'Xiaomi Amazfit GTS', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'male', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '43', 'po_brand' => 'Xiaomi', 'po_category' => 'Đông hồ Daniel wellington', 'po_provider' => 'Công Ty TNHH Thời Gian Thành Phố'),
        15 => array('id' => '16', 'po_name' => 'Apple Watch Series3', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'female', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '12', 'po_brand' => 'Apple', 'po_category' => 'Đông hồ Daniel wellington', 'po_provider' => 'Công Ty TNHH MTV Thương Mại Dịch Vụ Phong Kim Anh'),
        16 => array('id' => '17', 'po_name' => 'Apple Watch Series4', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'male', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '42', 'po_brand' => 'Apple', 'po_category' => 'Đồng hồ Citizen', 'po_provider' => 'Công Ty Cổ Phần ENSA'),
        17 => array('id' => '18', 'po_name' => 'Apple Watch Series5 nhôm', 'po_description' => 'Theo dõi giấc ngủ, Đo nhịp tim, Tính lượng Calories tiêu thụ, Đếm số bước chân, Tính quãng đường chạy, Chế độ luyện tập, Nghe nhạc với tai nghe Bluetooth, Màn hình luôn hiển thị, Gọi điện trên đồng hồ,Từ chối cuộc gọi, Dự báo thời tiết, La bàn, Thay mặt đồng hồ, Nhận cuộc gọi, Tìm điện thoại', 'po_image' => '', 'po_gender' => 'female', 'po_hot' => '', 'po_info' => '', 'po_policy' => '', 'po_quantity' => '46', 'po_brand' => 'Apple', 'po_category' => 'Đồng hồ Epos swiss', 'po_provider' => 'Công Ty TNHH Thương Mại Lê Anh'),
    );
